### ISSUE TITLE
Craches for certain strings

### ISSUE THREAD

**Issue by zouhair** [blha303/getlyrics#4]
```
$ getlyrics "The evil powers of rock n' roll"
Traceback (most recent call last):
  File "/usr/bin/getlyrics", line 11, in <module>
    load_entry_point('getlyrics==2.1.1', 'console_scripts', 'getlyrics')()
  File "/usr/lib/python3.4/site-packages/getlyrics/getlyrics.py", line 78, in main
    pager(lyric)
  File "/usr/lib/python3.4/pydoc.py", line 1411, in pager
    pager(text)
  File "/usr/lib/python3.4/pydoc.py", line 1433, in <lambda>
    return lambda text: pipepager(text, 'less')
  File "/usr/lib/python3.4/pydoc.py", line 1457, in pipepager
    pipe.write(text)
TypeError: must be str, not None
```
But this work:

```
$ getlyrics "I still haven't found what I'm looking for by U2"
Results:
        0. I Still Haven't Found What I'm Looking For  by U2
        1. I Still Haven't Found What I'm Looking For originally by U2 by BONNIE TYLER
enter your choice:
```

Found it a cool little app but not being a programmer dunno how to fix it.

Thanks

**Comment by blha303** [comment]
I didn't accommodate for there being no results sometimes.
